version: "3"

services:
  backend:
    build:
      context: backend/RawPotion.Meals
      dockerfile: RawPotion.Meals.Api/Dockerfile
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - database

  database:
    build:
      context: database/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: somethingsecret_123
      RAWPOTION_MEALS_POSTGRES_USER_PASSWORD: somethingverysecret_123
    ports:
      - 5432:5432

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
