# fly.toml file generated for rawpotion-meals-backend-staging on 2021-08-21T14:03:08+02:00

app = "rawpotion-meals-backend-staging"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  BACKEND_BASE_URL = "https://rawpotion-meals-backend-staging.fly.dev"
  FRONTEND_BASE_URL = "https://rawpotion-meals-frontend-staging.fly.dev"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
