name: End to end tests

on: [push]

jobs:
  e2e-docker-compose-up:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the docker-compose stack
        env:
          CI: true
          CYPRESS_BASE_URL: http://frontend:3000
        run: >-
          docker-compose -f docker-compose.e2e.yml run
          -e CYPRESS_BASE_URL=\${CYPRESS_BASE_URL}
          e2e 
